### ISSUE TITLE
Magic link request fails

### ISSUE THREAD

**Issue by Dakes** [bob6664569/claude-sync#2]
When trying to login I unfortunately get this console output:
```
> claude-sync@1.0.0 start
> electron .

Gtk-Message: 16:56:45.222: Failed to load module "colorreload-gtk-module"
Gtk-Message: 16:56:45.222: Failed to load module "window-decorations-gtk-module"
[30116:1021/165645.232974:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[30116:1021/165645.232992:ERROR:select_file_dialog_linux_portal.cc(291)] Failed to read portal version property
Store initialized
[30154:1021/165646.866031:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
API request failed: Invalid URL
Error sending magic link: Invalid URL
Error requesting TOTP: TypeError: Invalid URL
    at new URL (node:internal/url:797:36)
    at dispatchHttpRequest (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:2766:20)
    at /tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:2686:5
    at new Promise (<anonymous>)
    at wrapAsync (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:2666:10)
    at http (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:2704:10)
    at Axios.dispatchRequest (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:4110:10)
    at async Axios.request (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:4257:14)
    at async ClaudeAPIClient.sendMagicLink (/tmp/claude-sync/src/main/api-client.js:61:30)
    at async /tmp/claude-sync/src/main/ipc-handlers.js:91:3
2
    at Axios.request (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:4262:41)
    at async ClaudeAPIClient.sendMagicLink (/tmp/claude-sync/src/main/api-client.js:61:30)
    at async /tmp/claude-sync/src/main/ipc-handlers.js:91:32
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537) {
  code: 'ERR_INVALID_URL',
  input: '/auth/send_magic_link'
}
[30154:1021/165659.898390:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[30154:1021/165659.899781:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
If relevant, I am running on Arch Linux and Hyprland/Wayland

**Comment by bob6664569** [comment]
Did you create the .env file at the project's root? That would explain the incorrect URL 🤔

**Comment by Dakes** [comment]
Yes, with the content described in the Readme: `API_URL=https://api.claude.ai/api/`

**Comment by Dakes** [comment]
That error was caused, because the api url was referenced in the code by API_BASE_URL. So I adjusted the .env
But now I get this error:

```
> claude-sync@1.0.0 start
> electron .

Gtk-Message: 18:33:30.516: Failed to load module "colorreload-gtk-module"
Gtk-Message: 18:33:30.516: Failed to load module "window-decorations-gtk-module"
[179116:1022/183330.526927:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[179116:1022/183330.526947:ERROR:select_file_dialog_linux_portal.cc(291)] Failed to read portal version property
Store initialized
CLAUDE.baseURL https://api.claude.ai/api/
API request failed: {
  type: 'error',
  error: {
    type: 'invalid_request_error',
    message: 'recaptcha_site_key: Field required'
  }
}
Error sending magic link: {
  type: 'error',
  error: {
    type: 'invalid_request_error',
    message: 'recaptcha_site_key: Field required'
  }
}
Error requesting TOTP: AxiosError: Request failed with status code 400
    at settle (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:2015:12)
    at IncomingMessage.handleStreamEnd (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:3131:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/tmp/claude-sync/node_modules/axios/dist/node/axios.cjs:4262:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ClaudeAPIClient.sendMagicLink (/tmp/claude-sync/src/main/api-client.js:62:30)
    at async /tmp/claude-sync/src/main/ipc-handlers.js:91:32
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83537) {
  code: 'ERR_BAD_REQUEST',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http', 'fetch' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': 'application/json',
      'User-Agent': 'PostmanRuntime/7.41.0',
      'Postman-Token': 'ac8a7bcc-f2f8-46a1-b3f7-b6187e3043c6',
      'Content-Length': '94',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'https://api.claude.ai/api/',
    jar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: true,
      store: { idx: [Object: null prototype] {
        'claude.ai': [Object: null prototype] {
          '/': [Object: null prototype] {
            __cf_bm: Cookie="__cf_bm=dygqujGvLWapQUuiyV3MsXmI00VGmArv7VuMxinmazg-1729614891-1.0.1.1-7Ms5tHigE.eL__93kidBlYXI_P7Az0ebrhMVFejEHUScE4B8WUcklK0rRMZw.NM6BCl4bN.e6iWlPfADEUeFTw; Expires=Tue, 22 Oct 2024 17:04:51 GMT; Domain=claude.ai; Path=/; Secure; HttpOnly; hostOnly=false; aAge=12ms; cAge=12ms"
          }
        }
      } },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    },
    withCredentials: true,
    method: 'post',
    url: '/auth/send_magic_link',
    data: '{"utc_offset":-120,"email_address":"redacted@email.com","recaptcha_token":"","source":"claude"}',
    httpAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype] {},
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 0,
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: [Object]
    },
    httpsAgent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: [Object]
    }
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '94',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'api.claude.ai',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'api.claude.ai',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _writableState: [WritableState],
      allowHalfOpen: false,
      _maxListeners: undefined,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      autoSelectFamilyAttemptedAddresses: [Array],
      [Symbol(alpncallback)]: null,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 142,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /api/auth/send_magic_link HTTP/1.1\r\n' +
      'Accept: */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: PostmanRuntime/7.41.0\r\n' +
      'Postman-Token: ac8a7bcc-f2f8-46a1-b3f7-b6187e3043c6\r\n' +
      'Content-Length: 94\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'Host: api.claude.ai\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: CookieAgent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(cookieOptions)]: [Object]
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: '/api/auth/send_magic_link',
    _ended: true,
    res: IncomingMessage {
      _events: [Object],
      _readableState: [ReadableState],
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 400,
      statusMessage: 'Bad Request',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      _eventsCount: 4,
      responseUrl: 'https://api.claude.ai/api/auth/send_magic_link',
      redirects: [],
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 28,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.claude.ai',
    protocol: 'https:',
    _implicitHeader: [Function (anonymous)],
    emit: [Function (anonymous)],
    _redirectable: Writable {
      _events: [Object],
      _writableState: [WritableState],
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 94,
      _requestBodyBuffers: [],
      _eventsCount: 3,
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://api.claude.ai/api/auth/send_magic_link',
      [Symbol(shapeMode)]: true,
      [Symbol(kCapture)]: false
    },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'postman-token': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kHighWaterMark)]: 16384,
    [Symbol(kRejectNonStandardBodyWrites)]: false,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 400,
    statusText: 'Bad Request',
    headers: Object [AxiosHeaders] {
      date: 'Tue, 22 Oct 2024 16:34:51 GMT',
      'content-type': 'application/json',
      'content-length': '104',
      connection: 'close',
      'x-should-retry': 'false',
      'request-id': 'req_018qUz8boVbP8PR69tPuRt7H',
      'x-cloud-trace-context': '23aa4adb9a7f576c04e004eaa1cea763',
      via: '1.1 google',
      'alt-svc': 'h3=":443"; ma=86400',
      'cf-cache-status': 'DYNAMIC',
      'set-cookie': [Array],
      'x-robots-tag': 'none',
      server: 'cloudflare',
      'cf-ray': '8d6ae5aeae0c9264-MUC'
    },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [Object [AxiosHeaders]],
      baseURL: 'https://api.claude.ai/api/',
      jar: [CookieJar],
      withCredentials: true,
      method: 'post',
      url: '/auth/send_magic_link',
      data: '{"utc_offset":-120,"email_address":"redacted@email.com","recaptcha_token":"","source":"claude"}',
      httpAgent: [CookieAgent],
      httpsAgent: [CookieAgent]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '94',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'POST /api/auth/send_magic_link HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: PostmanRuntime/7.41.0\r\n' +
        'Postman-Token: ac8a7bcc-f2f8-46a1-b3f7-b6187e3043c6\r\n' +
        'Content-Length: 94\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: api.claude.ai\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [CookieAgent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/api/auth/send_magic_link',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.claude.ai',
      protocol: 'https:',
      _implicitHeader: [Function (anonymous)],
      emit: [Function (anonymous)],
      _redirectable: [Writable],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    data: { type: 'error', error: [Object] }
  }
}
```

**Comment by bob6664569** [comment]
Updated the `README.md`, you should add `RECAPTCHA_SITE_KEY` too (a random value seems to do the job... They obviously aren't using it 😅)
